# Generated by Django 3.2.9 on 2021-12-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.TextField(blank=True, max_length=15),
        ),
    ]
