# Generated by Django 3.2.9 on 2021-12-06 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('cnpj', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=15)),
                ('horaInicio', models.TimeField()),
                ('horaFim', models.TimeField()),
                ('logradouro', models.CharField(max_length=250)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=25)),
                ('cep', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=250)),
                ('observacao', models.CharField(max_length=250)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=250)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=250)),
                ('capacidade', models.IntegerField()),
                ('ehPreferencial', models.BooleanField()),
                ('equipamentos', models.ManyToManyField(to='campus.Equipamento')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.predio')),
            ],
        ),
    ]
