# Generated by Django 3.2.9 on 2021-12-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='observacao',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='sala',
            name='ehPreferencial',
            field=models.BooleanField(verbose_name='É preferencial para aulas?'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='equipamentos',
            field=models.ManyToManyField(blank=True, to='campus.Equipamento'),
        ),
    ]
