# Generated by Django 3.2.9 on 2021-12-14 21:20

from django.db import migrations, models
import reservas.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_auto_20211213_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='dataFim',
            field=models.DateField(validators=[reservas.models.validate_data], verbose_name='Data Fim'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dataInicio',
            field=models.DateField(validators=[reservas.models.validate_data], verbose_name='Data Inicio'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horaFim',
            field=models.TimeField(validators=[reservas.models.validate_hora], verbose_name='Hora Fim'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horaInicio',
            field=models.TimeField(validators=[reservas.models.validate_hora], verbose_name='Hora Inicio'),
        ),
    ]
