# Generated by Django 3.2.9 on 2021-12-14 21:40

from django.db import migrations, models
import reservas.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_auto_20211214_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='dataFim',
            field=models.DateField(validators=[reservas.models.validate_periodo], verbose_name='Data Fim'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='dataInicio',
            field=models.DateField(validators=[reservas.models.validate_periodo], verbose_name='Data Inicio'),
        ),
    ]
