# Generated by Django 3.2.9 on 2021-12-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_auto_20211214_1820'),
        ('reservas', '0005_auto_20211214_1840'),
    ]

    operations = [
    ]
