# Generated by Django 3.2.9 on 2021-12-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_merge_0004_auto_20211214_1820_0005_auto_20211214_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='dataFim',
            field=models.DateField(verbose_name='Data Fim'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='dataInicio',
            field=models.DateField(verbose_name='Data Inicio'),
        ),
    ]
